"""
===============================================================================
GeoSentinel AI

Script:
    train.py

Description:
    Production TorchGeo + PyTorch Lightning training pipeline.

    Architecture:
    - TorchGeo NonGeoDataset for .npy patches (real Sentinel-2 data)
    - TorchGeo SemanticSegmentationTask for distributed training
    - DeepLabV3+ (ResNet50) for semantic segmentation
    - U-Net (ResNet34) for change detection
    - Dice + Focal combined loss
    - CosineAnnealingLR scheduler
    - ModelCheckpoint on val_miou

    Usage:
        python scripts/train.py --model deeplabv3plus --epochs 100
        python scripts/train.py --model unet --task change_detection --epochs 50

Author:
    Karthikeya Bhamidipati
===============================================================================
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import torch
import lightning as L
from torch.utils.data import DataLoader
from lightning.pytorch.callbacks import (
    ModelCheckpoint,
    LearningRateMonitor,
    EarlyStopping,
)
from torchgeo.datasets import NonGeoDataset
from torchgeo.trainers import SemanticSegmentationTask

# ── project root on sys.path ─────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.models.unet import NUM_CLASSES, DEFAULT_IN_CHANNELS, LAND_COVER_NAMES


# =============================================================================
# TorchGeo NonGeoDataset for .npy patches
# =============================================================================


class GeoSentinelPatchDataset(NonGeoDataset):
    """
    TorchGeo NonGeoDataset wrapping .npy image/mask patch pairs.

    Patches are generated by generate_real_dataset.py using the exact
    same preprocessing pipeline (Cloud Mask → Resample → Normalize →
    Feature Engineering) that runs during production inference.

    Parameters
    ----------
    root : Path
        Directory containing image_XXXX.npy and mask_XXXX.npy files.
    augment : bool
        If True, apply geometric augmentations (flips + rotations).
    """

    def __init__(self, root: Path, augment: bool = False) -> None:
        super().__init__()
        self.root = Path(root)
        self.augment = augment
        self.image_files = sorted(self.root.glob("image_*.npy"))
        if len(self.image_files) == 0:
            raise FileNotFoundError(
                f"No image_*.npy files found in {self.root}. "
                f"Run scripts/generate_real_dataset.py first."
            )

    def __len__(self) -> int:
        return len(self.image_files)

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        img_path = self.image_files[idx]
        mask_path = self.root / img_path.name.replace("image_", "mask_")

        image = np.load(img_path)  # (12, H, W) float32
        mask = np.load(mask_path)  # (H, W) int64

        # Geometric augmentation (spectral values are NEVER altered)
        if self.augment:
            if np.random.random() > 0.5:
                image = np.flip(image, axis=2).copy()
                mask = np.flip(mask, axis=1).copy()
            if np.random.random() > 0.5:
                image = np.flip(image, axis=1).copy()
                mask = np.flip(mask, axis=0).copy()
            k = np.random.randint(0, 4)
            if k > 0:
                image = np.rot90(image, k=k, axes=(1, 2)).copy()
                mask = np.rot90(mask, k=k, axes=(0, 1)).copy()

        # Safety: replace NaN/Inf (should not exist but defensive)
        image = np.nan_to_num(image, nan=0.0, posinf=0.0, neginf=0.0)

        # TorchGeo expects dict with 'image' and 'mask' keys
        return {
            "image": torch.from_numpy(image.copy()).float(),
            "mask": torch.from_numpy(mask.copy()).long(),
        }


# =============================================================================
# TorchGeo LightningDataModule
# =============================================================================


class GeoSentinelDataModule(L.LightningDataModule):
    """
    TorchGeo-compatible DataModule for GeoSentinel patch datasets.

    Expects the following directory structure:
        data_dir/
            train/
                image_0000.npy, mask_0000.npy, ...
            val/
                image_0000.npy, mask_0000.npy, ...
    """

    def __init__(
        self,
        data_dir: Path,
        batch_size: int = 8,
        num_workers: int = 0,
    ):
        super().__init__()
        self.data_dir = Path(data_dir)
        self.batch_size = batch_size
        self.num_workers = num_workers

    def setup(self, stage: str | None = None):
        train_dir = self.data_dir / "train"
        val_dir = self.data_dir / "val"

        if not train_dir.exists():
            raise FileNotFoundError(
                f"Training directory not found: {train_dir}. "
                f"Run scripts/generate_real_dataset.py first."
            )
        if not val_dir.exists():
            print(f"[WARN] No validation directory found at {val_dir}. Using train as val.")
            val_dir = train_dir

        self.train_ds = GeoSentinelPatchDataset(train_dir, augment=True)
        self.val_ds = GeoSentinelPatchDataset(val_dir, augment=False)

        print(f"  Train samples: {len(self.train_ds)}")
        print(f"  Val samples:   {len(self.val_ds)}")

    def train_dataloader(self):
        return DataLoader(
            self.train_ds,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=True,
            drop_last=True,
            persistent_workers=True,
        )

    def val_dataloader(self):
        return DataLoader(
            self.val_ds,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=True,
            persistent_workers=True,
        )


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    parser = argparse.ArgumentParser(
        description="GeoSentinel AI — TorchGeo Training Pipeline"
    )
    parser.add_argument(
        "--model", type=str, default="deeplabv3plus",
        choices=["unet", "deeplabv3plus"],
        help="Model architecture (default: deeplabv3plus)",
    )
    parser.add_argument(
        "--data-dir", type=Path,
        default=PROJECT_ROOT / "data" / "benchmark" / "real",
        help="Root data directory containing train/ and val/ subdirectories",
    )
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument(
        "--encoder", type=str, default=None,
        help="Encoder backbone (default: resnet50 for deeplabv3+, resnet34 for unet)",
    )
    parser.add_argument(
        "--resume-from", type=str, default=None,
        help="Path to a .ckpt file to resume training from",
    )
    parser.add_argument("--num-workers", type=int, default=12)
    args = parser.parse_args()

    L.seed_everything(42, workers=True)

    # Default encoders
    if args.encoder is None:
        args.encoder = "resnet50" if args.model == "deeplabv3plus" else "resnet34"

    # Map model name for TorchGeo if necessary
    tg_model_name = args.model
    if tg_model_name == "deeplabv3plus":
        tg_model_name = "deeplabv3+"

    print("=" * 64)
    print(f"  GeoSentinel AI — TorchGeo Training Pipeline")
    print(f"  Model:   {tg_model_name} ({args.encoder})")
    print(f"  Input:   {DEFAULT_IN_CHANNELS} channels")
    print(f"  Classes: {NUM_CLASSES} ({', '.join(LAND_COVER_NAMES.values())})")
    print(f"  Epochs:  {args.epochs}")
    print(f"  LR:      {args.lr}")
    print("=" * 64)

    # ── DataModule ─────────────────────────────────────────────────────
    datamodule = GeoSentinelDataModule(
        args.data_dir,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
    )

    # ── TorchGeo SemanticSegmentationTask ──────────────────────────────
    # This wraps the SMP model + loss + metrics into a single Lightning module
    task = SemanticSegmentationTask(
        model=tg_model_name,
        backbone=args.encoder,
        weights=True,                       # ImageNet pretrained encoder
        in_channels=DEFAULT_IN_CHANNELS,    # 12 channels
        num_classes=NUM_CLASSES,            # 6 classes
        loss="focal",                       # Focal loss handles class imbalance
        lr=args.lr,
        patience=10,                        # LR scheduler patience
    )

    # ── Callbacks ──────────────────────────────────────────────────────
    checkpoint_dir = PROJECT_ROOT / "data" / "weights"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    callbacks = [
        ModelCheckpoint(
            dirpath=str(checkpoint_dir),
            filename=f"{args.model}_best",
            monitor="val_loss",
            mode="min",
            save_top_k=1,
            verbose=True,
        ),
        LearningRateMonitor(logging_interval="epoch"),
        EarlyStopping(
            monitor="val_loss",
            patience=20,
            mode="min",
            verbose=True,
        ),
    ]

    # ── Custom callback to also save as .pt for orchestrator ───────────
    class OrchestratorCheckpointCallback(L.Callback):
        """
        Saves a standalone .pt file (just the model state_dict) that
        the orchestrator can load without Lightning.
        """
        def __init__(self, save_path: Path):
            self.save_path = save_path
            self.best_val_loss = float("inf")

        def on_validation_epoch_end(self, trainer, pl_module):
            val_loss = trainer.callback_metrics.get("val_loss")
            if val_loss is not None and val_loss < self.best_val_loss:
                self.best_val_loss = val_loss
                # Extract the SMP model from TorchGeo's task
                model_state = pl_module.model.state_dict()
                torch.save(
                    {"model_state_dict": model_state},
                    self.save_path,
                )
                print(f"  [BEST] Saved orchestrator checkpoint: {self.save_path}")

    orch_save_path = checkpoint_dir / f"{args.model}_best.pt"
    callbacks.append(OrchestratorCheckpointCallback(orch_save_path))

    # ── Trainer ────────────────────────────────────────────────────────
    trainer = L.Trainer(
        max_epochs=args.epochs,
        accelerator="auto",
        devices=1,
        precision="32-true",   # FP32 to prevent Sentinel-2 value overflow
        callbacks=callbacks,
        log_every_n_steps=5,
        enable_progress_bar=True,
    )

    print("\nStarting training...\n")
    trainer.fit(model=task, datamodule=datamodule, ckpt_path=args.resume_from)

    # ── Final summary ──────────────────────────────────────────────────
    print("\n" + "=" * 64)
    print(f"  Training complete!")
    print(f"  Best checkpoint: {orch_save_path}")
    print(f"  Lightning checkpoint: {checkpoint_dir / f'{args.model}_best.ckpt'}")
    print("=" * 64)


if __name__ == "__main__":
    main()
